#!/usr/bin/env bash

alias ga="git add"
alias gas="gh auth switch"
alias gb="git branch"
alias gbd="git branch -D"
alias gbdr="git push origin --delete"
alias gc="git commit"
alias gcm="git commit -m"
alias gco="git checkout"
alias gd="git diff"
alias gds="git diff --staged"
alias gf="git fetch"
alias gl="git log"
alias glo="git log --oneline"
alias gp="git pull"
alias gpom="gp origin main"
alias gpu="git push"
alias gpu2="gas && gpu && gas"
alias gr="git restore"
alias gs="git status"
alias gst="git stash"
alias gsw="git switch"
alias m="gco main && gp"
